name: Run tests and publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22, 23]
    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node-version }}"

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run tests
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --include=dev

      - name: Publish dev package
        run: npx pkg-pr-new publish
